; Auto-generated. Do not edit!


(cl:in-package tiago_custom_msgs-msg)


;//! \htmlinclude PickGoal.msg.html

(cl:defclass <PickGoal> (roslisp-msg-protocol:ros-message)
  ((use_aruco
    :reader use_aruco
    :initarg :use_aruco
    :type cl:boolean
    :initform cl:nil)
   (aruco_id
    :reader aruco_id
    :initarg :aruco_id
    :type cl:integer
    :initform 0)
   (pose
    :reader pose
    :initarg :pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass PickGoal (<PickGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tiago_custom_msgs-msg:<PickGoal> is deprecated: use tiago_custom_msgs-msg:PickGoal instead.")))

(cl:ensure-generic-function 'use_aruco-val :lambda-list '(m))
(cl:defmethod use_aruco-val ((m <PickGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago_custom_msgs-msg:use_aruco-val is deprecated.  Use tiago_custom_msgs-msg:use_aruco instead.")
  (use_aruco m))

(cl:ensure-generic-function 'aruco_id-val :lambda-list '(m))
(cl:defmethod aruco_id-val ((m <PickGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago_custom_msgs-msg:aruco_id-val is deprecated.  Use tiago_custom_msgs-msg:aruco_id instead.")
  (aruco_id m))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <PickGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago_custom_msgs-msg:pose-val is deprecated.  Use tiago_custom_msgs-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickGoal>) ostream)
  "Serializes a message object of type '<PickGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'use_aruco) 1 0)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'aruco_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'aruco_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'aruco_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'aruco_id)) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickGoal>) istream)
  "Deserializes a message object of type '<PickGoal>"
    (cl:setf (cl:slot-value msg 'use_aruco) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'aruco_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'aruco_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'aruco_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'aruco_id)) (cl:read-byte istream))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickGoal>)))
  "Returns string type for a message object of type '<PickGoal>"
  "tiago_custom_msgs/PickGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickGoal)))
  "Returns string type for a message object of type 'PickGoal"
  "tiago_custom_msgs/PickGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickGoal>)))
  "Returns md5sum for a message object of type '<PickGoal>"
  "b97fd92d46d76c34e247152503c365d6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickGoal)))
  "Returns md5sum for a message object of type 'PickGoal"
  "b97fd92d46d76c34e247152503c365d6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickGoal>)))
  "Returns full string definition for message of type '<PickGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%bool use_aruco~%uint32 aruco_id # Specify which aruco id to pick~%geometry_msgs/Pose pose ~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickGoal)))
  "Returns full string definition for message of type 'PickGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%bool use_aruco~%uint32 aruco_id # Specify which aruco id to pick~%geometry_msgs/Pose pose ~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickGoal>))
  (cl:+ 0
     1
     4
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PickGoal
    (cl:cons ':use_aruco (use_aruco msg))
    (cl:cons ':aruco_id (aruco_id msg))
    (cl:cons ':pose (pose msg))
))
