; Auto-generated. Do not edit!


(cl:in-package tiago_custom_msgs-msg)


;//! \htmlinclude PickFeedback.msg.html

(cl:defclass <PickFeedback> (roslisp-msg-protocol:ros-message)
  ((running
    :reader running
    :initarg :running
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PickFeedback (<PickFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tiago_custom_msgs-msg:<PickFeedback> is deprecated: use tiago_custom_msgs-msg:PickFeedback instead.")))

(cl:ensure-generic-function 'running-val :lambda-list '(m))
(cl:defmethod running-val ((m <PickFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tiago_custom_msgs-msg:running-val is deprecated.  Use tiago_custom_msgs-msg:running instead.")
  (running m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickFeedback>) ostream)
  "Serializes a message object of type '<PickFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'running) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickFeedback>) istream)
  "Deserializes a message object of type '<PickFeedback>"
    (cl:setf (cl:slot-value msg 'running) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickFeedback>)))
  "Returns string type for a message object of type '<PickFeedback>"
  "tiago_custom_msgs/PickFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickFeedback)))
  "Returns string type for a message object of type 'PickFeedback"
  "tiago_custom_msgs/PickFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickFeedback>)))
  "Returns md5sum for a message object of type '<PickFeedback>"
  "1b92741eacf4a1b0d041863bc6d55e7f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickFeedback)))
  "Returns md5sum for a message object of type 'PickFeedback"
  "1b92741eacf4a1b0d041863bc6d55e7f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickFeedback>)))
  "Returns full string definition for message of type '<PickFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%bool running~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickFeedback)))
  "Returns full string definition for message of type 'PickFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%bool running~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PickFeedback
    (cl:cons ':running (running msg))
))
