// Generated by gencpp from file tiago_custom_msgs/PickGoal.msg
// DO NOT EDIT!


#ifndef TIAGO_CUSTOM_MSGS_MESSAGE_PICKGOAL_H
#define TIAGO_CUSTOM_MSGS_MESSAGE_PICKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace tiago_custom_msgs
{
template <class ContainerAllocator>
struct PickGoal_
{
  typedef PickGoal_<ContainerAllocator> Type;

  PickGoal_()
    : use_aruco(false)
    , aruco_id(0)
    , pose()  {
    }
  PickGoal_(const ContainerAllocator& _alloc)
    : use_aruco(false)
    , aruco_id(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _use_aruco_type;
  _use_aruco_type use_aruco;

   typedef uint32_t _aruco_id_type;
  _aruco_id_type aruco_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PickGoal_

typedef ::tiago_custom_msgs::PickGoal_<std::allocator<void> > PickGoal;

typedef boost::shared_ptr< ::tiago_custom_msgs::PickGoal > PickGoalPtr;
typedef boost::shared_ptr< ::tiago_custom_msgs::PickGoal const> PickGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago_custom_msgs::PickGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tiago_custom_msgs::PickGoal_<ContainerAllocator1> & lhs, const ::tiago_custom_msgs::PickGoal_<ContainerAllocator2> & rhs)
{
  return lhs.use_aruco == rhs.use_aruco &&
    lhs.aruco_id == rhs.aruco_id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tiago_custom_msgs::PickGoal_<ContainerAllocator1> & lhs, const ::tiago_custom_msgs::PickGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tiago_custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b97fd92d46d76c34e247152503c365d6";
  }

  static const char* value(const ::tiago_custom_msgs::PickGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb97fd92d46d76c34ULL;
  static const uint64_t static_value2 = 0xe247152503c365d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago_custom_msgs/PickGoal";
  }

  static const char* value(const ::tiago_custom_msgs::PickGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"bool use_aruco\n"
"uint32 aruco_id # Specify which aruco id to pick\n"
"geometry_msgs/Pose pose \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::tiago_custom_msgs::PickGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.use_aruco);
      stream.next(m.aruco_id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago_custom_msgs::PickGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago_custom_msgs::PickGoal_<ContainerAllocator>& v)
  {
    s << indent << "use_aruco: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_aruco);
    s << indent << "aruco_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.aruco_id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO_CUSTOM_MSGS_MESSAGE_PICKGOAL_H
