// Generated by gencpp from file tiago_custom_msgs/PickFeedback.msg
// DO NOT EDIT!


#ifndef TIAGO_CUSTOM_MSGS_MESSAGE_PICKFEEDBACK_H
#define TIAGO_CUSTOM_MSGS_MESSAGE_PICKFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tiago_custom_msgs
{
template <class ContainerAllocator>
struct PickFeedback_
{
  typedef PickFeedback_<ContainerAllocator> Type;

  PickFeedback_()
    : running(false)  {
    }
  PickFeedback_(const ContainerAllocator& _alloc)
    : running(false)  {
  (void)_alloc;
    }



   typedef uint8_t _running_type;
  _running_type running;





  typedef boost::shared_ptr< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PickFeedback_

typedef ::tiago_custom_msgs::PickFeedback_<std::allocator<void> > PickFeedback;

typedef boost::shared_ptr< ::tiago_custom_msgs::PickFeedback > PickFeedbackPtr;
typedef boost::shared_ptr< ::tiago_custom_msgs::PickFeedback const> PickFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tiago_custom_msgs::PickFeedback_<ContainerAllocator1> & lhs, const ::tiago_custom_msgs::PickFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.running == rhs.running;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tiago_custom_msgs::PickFeedback_<ContainerAllocator1> & lhs, const ::tiago_custom_msgs::PickFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tiago_custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b92741eacf4a1b0d041863bc6d55e7f";
  }

  static const char* value(const ::tiago_custom_msgs::PickFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b92741eacf4a1b0ULL;
  static const uint64_t static_value2 = 0xd041863bc6d55e7fULL;
};

template<class ContainerAllocator>
struct DataType< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tiago_custom_msgs/PickFeedback";
  }

  static const char* value(const ::tiago_custom_msgs::PickFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"bool running\n"
;
  }

  static const char* value(const ::tiago_custom_msgs::PickFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.running);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tiago_custom_msgs::PickFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tiago_custom_msgs::PickFeedback_<ContainerAllocator>& v)
  {
    s << indent << "running: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.running);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIAGO_CUSTOM_MSGS_MESSAGE_PICKFEEDBACK_H
